# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get project version
      uses: lllggghhhaaa/WaxDotnetVersionFinder@release
      id: project-version
      with:
        path: /home/runner/work/WaxMapArt/WaxMapArt/WaxMapArt.Avalonia.Desktop/WaxMapArt.Avalonia.Desktop.csproj
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Publish win-x64
      run: dotnet publish /home/runner/work/WaxMapArt/WaxMapArt/WaxMapArt.Avalonia.Desktop/WaxMapArt.Avalonia.Desktop.csproj -r win-x64 -c Release -o publish/win-x64 --sc
   
    - name: Publish linux-x64
      run: dotnet publish /home/runner/work/WaxMapArt/WaxMapArt/WaxMapArt.Avalonia.Desktop/WaxMapArt.Avalonia.Desktop.csproj -r linux-x64 -c Release -o publish/linux-x64 --sc

    - name: Zip win-x64
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r /home/runner/work/WaxMapArt/WaxMapArt/publish/artifacts/win-x64.zip . -i /home/runner/work/WaxMapArt/WaxMapArt/publish/win-x64

    - name: Zip linux-x64
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r /home/runner/work/WaxMapArt/WaxMapArt/publish/artifacts/linux-x64.zip . -i /home/runner/work/WaxMapArt/WaxMapArt/publish/linux-x64

    - name: Create Folder
      run: |
        mkdir /home/runner/work/WaxMapArt/WaxMapArt/publish/artifacts/
   
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        name: ${{steps.project-version.outputs.version}}
        artifacts: "/home/runner/work/WaxMapArt/WaxMapArt/publish/artifacts/*"
            
